---
abstract: 'Core library as Role (Moo) to process map data.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Map-Tube
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/Manwar/Map-Tube.git
version: 2.30
