---
abstract: 'A very simple perl interface to the London Tube Map.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Map-Tube
provides:
  Map::Tube:
    file: lib/Map/Tube.pm
    version: 0.05
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
